server:
  port: 23709

spring:
  datasource:
    url: jdbc:mysql://172.17.4.24:3306/convenientlyshot-dalian?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: siwei@mysql1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: personsys-redis-dalian
#    database: 11
#    port: 6379
#    password: siwei@redis1234

  redis:
    host: 172.17.4.23
    database: 6
    port: 16379
    password: siwei@reids

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
myValue:
  authAddress: http://58.56.207.43:9500/token/searchForUserByToken
  isLoginAddress: http://172.17.4.24:6033/isLogin/
