spring:
  datasource:
    url: jdbc:mysql://192.168.246.129:3306/xiamen_quality-inspection?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.246.129
    database: 3
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



myValue:
  authAddress: http://58.56.207.43:6507/token/searchForUserByToken
  #修改内容 每个项目对应的地址不同
  isLoginAddress: http://58.56.207.43:6510/isLogin/


